name: Extract Stock Firmware (dumpyara)

on:
  workflow_dispatch:
    inputs:
      firmware_stock_url:
        description: 'URL of the firmware package (tgz/zip/etc)'
        required: true
        default: 'https://xm04.space/MyUrLiwlJzsOOD0BMz8GIywRNEEOFTAINBUpIzE/KzUOPDJBGyEELhsQMDUxIS0eGz8dLzE/Hx4OFQRBDjwfDDQ8Kw8bFQQeNBIuAA4KBCYzPC0wMQofHg4KHwwxED0kQh4nLycSIh4nFkIvJxIXPEIJPUADLTUfDj8rDCwKFzUbIT0cMxUXHBsRAAw5CgQmPBEtIzkVNC0sMD0kQh4nLycSIh4nFkIvJxIXPEIJPUADLTUfPB4HQScCOUEfHh0/DgIdQScWHS8nFhocJwM5LycEPQgxLTowGxUyNRsWCT8fHiwwDiArIAsgADonAywiBQMUHgUWBzAfHRMT'

      firmware_donar_url:
        description: 'URL of the firmware package (tgz/zip/etc)'
        required: true
        default: 'https://xm04.space/MyUrLiwlJzsOOD0BMz8GIywRNEEOFTAINBUpIzE/KzUOPDJBGyEELhsQMDUxIS0eGz8dLzE/Hx4OFQRBDjwfDDQ8Kw8bFQQeNBIuAA4KBCYzPC0wMQofHg4KHwwxED0kQh4nLycSIh4nFkIvJxIXPEIJPUADLTUfDj8rDCwKFzUbIT0cMxUXHBsRAAw5CgQmPBEtIzkVNC0sMD0kQh4nLycSIh4nFkIvJxIXPEIJPUADLTUfPB4HQScCOUEfHh0/DgIdQScWHS8nFhocJwM5LycEPQgxLTowGxUyNRsWCT8fHiwwDiArIAsgADonAywiBQMUHgUWBzAfHRMT'
permissions:
  contents: write

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/local/.ghcup
          sudo docker image prune -a -f || true
          df -h

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install dumpyara and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk-libsparse-utils erofs-utils e2tools e2fsprogs \
            brotli p7zip-full lz4 cpio python3-pip python3-setuptools git-lfs
          pip install --break-system-packages dumpyara
          git lfs install

      - name: Download stock firmware package
        run: |
          curl -L --fail --retry 5 --retry-delay 5 --retry-all-errors \
            --speed-time 30 --speed-limit 5000 \
            -o firmware_package.tgz "${{ github.event.inputs.firmware_stock_url }}"
          ls -lh firmware_package.tgz

      - name: Download donar firmware package
        run: |
          curl -L --fail --retry 5 --retry-delay 5 --retry-all-errors \
            --speed-time 30 --speed-limit 5000 \
            -o firmware_donar_package.tgz "${{ github.event.inputs.firmware_donar_url }}"
          ls -lh firmware_donar_package.tgz

      - name: Run dumpyara(stock)
        run: |
          mkdir -p dump_output
          cd dump_output
          python3 -m dumpyara ../firmware_package.tgz
          echo "---- dumpyara output ----"
          find . -maxdepth 2

      - name: Run dumpyara(donar)
        run: |
          mkdir -p dump_donar_output
          cd dump_donar_output
          python3 -m dumpyara ../firmware_donar_package.tgz
          echo "---- dumpyara output ----"
          find . -maxdepth 2


      - name: make workspace
        run: |
             cp -R dump_output/firmware_package stock
             rm -rf dump_output/firmware_package
             cp -R dump_donar_output/firmware_donar_package donar
             rm -rf dump_donar_output/firmware_donar_package 
             
             rm -rf stock/init_boot
             rm -rf stock/boot
             rm -rf stock/vendor_boot
             rm -rf donar/init_boot
             rm -rf donar/boot
             rm -rf donar/vendor_boot

      - name: checking
        run: |
             ls -lah stock

             ls -lah stock
