name: Rom Porter

on:
  workflow_dispatch:
    inputs:
      firmware_stock_url:
        description: 'URL of the Stock firmware package (tgz/zip/etc)'
        required: true
        default: 'https://xm01.space/MyUrLiwlJzsOOD0BMz8GIywRNEEOFTAINBUpIzE/KzUOPDJBGyEELhsQMDUxIS0eGz8dLzE/Hx4OFQRBDjwfDDQ8Kw8bFQQeNBIuAA4KBCYzPC0wMQofHg4KHwwxED0kQh4HLycSIjgnFgcvJxIXFUIJPUADLTUfDj8rDCwKFzUbIT0cMxUXHBsRAAw5CgQmDhU9LjkyPQo0FQAmDkI9AycBIkEOAgdBJwEiQQ4tGwYDLi0FFQkuIzQ8Hy0sAS4AHxAiQQ4DKTAfFRspJwIHHjkDQi8LCi1BHCVBAB8eKUEfAxQeBQMpOA=='
      firmware_donor_url:
        description: 'URL of the Donor firmware package (tgz/zip/etc)'
        required: true
        default: 'https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS4.0.0.3.XPSCNXM/warhol-ota_full-OS4.0.0.3.XPSCNXM-user-17.0-d7c0b752aa.zip'

permissions:
  contents: write

jobs:
  port:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/local/.ghcup
          sudo docker image prune -a -f || true
          df -h

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install dependencies and lpmake
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk-libsparse-utils erofs-utils e2tools e2fsprogs \
            brotli p7zip-full lz4 cpio python3-pip python3-setuptools git-lfs curl
          pip install --break-system-packages dumpyara 
          git clone https://github.com/Exynos-nigg/lpunpack-lpmake-mirror.git lpbinary
          cd lpbinary
          bash install.sh
          
 
      - name: Download firmware packages
        run: |
          
          curl -L --fail --retry 5 --retry-delay 5 -o firmware_donor.zip "${{ github.event.inputs.firmware_donor_url }}"
          

      - name: Dump donor firmware
        run: |
          mkdir -p dump_donor
          cd dump_donor
          python3 -m dumpyara ../firmware_donor.zip
          cd ..
          rm -f firmware_donor.zip

      - name: Setup workspace folders
        run: |
          mv dump_donor/firmware_donor donor
          rm -rf dump_donor

          # Prune non-dynamic partitions to conserve space
          rm -rf donor/boot* donor/vendor_boot* donor/init_boot* donor/dtbo* donor/rescue*

      
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Settings
          if-no-files-found: warn
          path: |
            donor/system_ext/priv-app/Settings/Settings.apk
          
